#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# copy config
if [[ ! -e /config/WebGrab++.config.xml ]]; then
    cp /defaults/WebGrab++.config.xml /config/
fi

if [[ ! -e /config/siteini.pack ]]; then
    cp -R /defaults/ini/siteini.pack /config/
fi

# warn user about changing name for crontab file
echo "******** Please use the file wg3-cron to adjust the scheduled time for running WebGrab++. wg-cron can now be deleted. ********"

# add cron file for running webgrab+plus
if [[ ! -e /config/wg3-cron ]]; then
    cp /defaults/wg3-cron /config/wg3-cron
fi

crontab -u abc /config/wg3-cron

mkdir -p /app/wg++/bin.net/WebGrab+Plus
mkdir -p /config/License
ln -sf /config/License /app/wg++/bin.net/WebGrab+Plus

# permissions
lsiown -R abc:abc \
    /app \
    /config \
    /data
